importer:
  course-member: Topxia\Service\Importer\CourseMemberImporter
  classroom-member: Topxia\Service\Importer\ClassroomMemberImporter

order:
  course:
    processor: Topxia\Service\Order\OrderProcessor\CourseOrderProcessor
    order_show_template: TopxiaWebBundle:Order:order-course.html.twig
  classroom:
    processor: Topxia\Service\Order\OrderProcessor\ClassroomOrderProcessor
    order_show_template: TopxiaWebBundle:Order:classroom.html.twig
  vip:
    processor: Topxia\Service\Order\OrderProcessor\VipOrderProcessor
    order_show_template: TopxiaWebBundle:Order:vip.html.twig
  coin:
    processor: Topxia\Service\Order\OrderProcessor\CoinOrderProcessor
  groupSell:
    processor: Topxia\Service\Order\OrderProcessor\GroupSellOrderProcessor
    order_show_template: GroupSellBundle:GroupSell:Order/group_sell.html.twig
