admin_roles:
    pattern:  /roles
    defaults: { _controller: PermissionBundle:Role:index }
    permissions: [admin_role_manage]

admin_role_create:
    pattern:  /role/create
    defaults: { _controller: PermissionBundle:Role:create }

admin_role_edit:
    pattern:  /role/{id}/edit
    defaults: { _controller: PermissionBundle:Role:edit }

admin_role_delete:
    pattern:  /role/{id}/delete
    defaults: { _controller: PermissionBundle:Role:delete }
    methods: [POST]

admin_role_show:
    pattern:  /role/{id}/show
    defaults: { _controller: PermissionBundle:Role:show }
    permissions: [admin_role_manage]

admin_role_check_name:
    pattern:  /role/checkName
    defaults: { _controller: PermissionBundle:Role:checkName }
    permissions: [admin_role_manage]

admin_role_check_code:
    pattern:  /role/checkCode
    defaults: { _controller: PermissionBundle:Role:checkCode }
    permissions: [admin_role_manage]