material_lib_browsing:
    pattern: /material/lib/browse
    defaults: { _controller: MaterialLibBundle:MaterialLib:index}

material_lib_show_browsing:
    pattern: /material/lib/show/browse
    defaults: { _controller: MaterialLibBundle:MaterialLib:showMyMaterialLibForm}

material_lib_my_sharing:
    pattern: /material/lib/my/sharing/show
    defaults: { _controller: MaterialLibBundle:MaterialLib:showShareForm }

material_lib_my_sharing_detail:
    pattern: /material/lib/my/sharing_detail/show
    defaults: { _controller: MaterialLibBundle:MaterialLib:historyDetailShow }

material_lib_my_sharing_users:
    pattern: /material/lib/my/sharing_users/show
    defaults: { _controller: MaterialLibBundle:MaterialLib:historyUserShow }

material_lib_my_sharing_contacts:
    pattern: /material/lib/recent/contacts
    defaults: { _controller: MaterialLibBundle:MaterialLib:findMySharingContacts }

material_lib_save_sharing:
    pattern: /material/lib/my/sharing/save
    defaults: { _controller: MaterialLibBundle:MaterialLib:saveShare }

material_tag_show_match:
    pattern: /material/lib/tag/match
    defaults: { _controller: MaterialLibBundle:MaterialLib:match }

material_lib_show_sharing_history:
    pattern: /material/lib/my/sharing/history
    defaults: { _controller: MaterialLibBundle:MaterialLib:showShareHistory }

material_lib_cancel_sharing:
    pattern: /material/lib/my/sharing/cancel
    defaults: { _controller: MaterialLibBundle:MaterialLib:cancelShare }

material_lib_save_collection:
    pattern: /material/lib/my/collection/save
    defaults: { _controller: MaterialLibBundle:MaterialLib:collect }

material_lib_file_preview:
    pattern:  /material/lib/file/{fileId}/preview
    defaults: { _controller: MaterialLibBundle:MaterialLib:preview }

material_edit:
    pattern:  /materiallib/{fileId}/edit
    defaults: { _controller: MaterialLibBundle:MaterialLib:edit }
    methods: [POST]

material_lib_file_player:
    pattern:  /material/lib/{fileId}/player
    defaults: { _controller: MaterialLibBundle:MaterialLib:player }

material_reconvert:
    pattern:  /material/lib/{globalId}/reconvert
    defaults: { _controller: MaterialLibBundle:MaterialLib:reconvert }

material_thumbnail_generate:
    pattern:  /material/lib/{globalId}/thumbnail/generate
    defaults: { _controller: MaterialLibBundle:MaterialLib:generateThumbnail }

material_lib_file_detail:
    pattern:  /material/lib/{fileId}/detail
    defaults: { _controller: MaterialLibBundle:MaterialLib:detail }

material_download:
    pattern:  /materiallib/{fileId}/download
    defaults: { _controller: MaterialLibBundle:MaterialLib:download }

material_delete:
    pattern:  /materiallib/{fileId}/delete
    defaults: { _controller: MaterialLibBundle:MaterialLib:delete }
    methods: [POST]

material_batch_delete:
    pattern: /materials/batch/delete
    defaults: { _controller: MaterialLibBundle:MaterialLib:batchDelete }
    methods: [POST]

material_delete_modal_show:
    pattern: /materials/delete/show
    defaults: { _controller: MaterialLibBundle:MaterialLib:deleteModalShow }
    methods: [POST]

material_batch_share:
    pattern: /materials/batch/share
    defaults: { _controller: MaterialLibBundle:MaterialLib:batchShare }
    methods: [POST]

material_unshare:
    pattern: /materiallib/{fileId}/unshare
    defaults: { _controller: MaterialLibBundle:MaterialLib:unshare }

material_batch_tag_show:
    pattern: /materials/batch/tag/show
    defaults: { _controller: MaterialLibBundle:MaterialLib:batchTagShow }

global_file_player:
   pattern:  /global_file/{globalId}/player
   defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:player }

global_file_hls_playlist:
    pattern:  /global_file/{globalId}/playlist/{token}.m3u8
    defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:playlist }

global_file_hls_stream:
    pattern:  /global_file/{globalId}/stream/{level}/{token}.m3u8
    defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:stream }

global_file_hls_clef:
    pattern:  /global_file/{globalId}/clef/{token}
    defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:clef }

global_file_ppt:
    pattern:  /global_file/{globalId}/ppt
    defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:ppt }

global_file_document:
    pattern:  /global_file/{globalId}/document
    defaults: { _controller: MaterialLibBundle:GlobalFilePlayer:document }
