parameters:
#    sensitive_word.example.class: Sensitive\SensitiveWordBundle\Example

services:
#    sensitive_word.example:
#        class: %sensitive_word.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
